### PR TITLE
sinkhorn GPU implementation

### PR DESCRIPTION
**Pull request by aje**
My implementation of sinkhorn GPU. To use the gpu version, it is first required to go inside the folder ot/gpu/cudamat and to launch the command:
`python3 setup.py install (or python for 2.7)`
cudamat itself requires to have installed cuda

I made a short script to compare the performances between normal sinkhorn and GPU sinkhorn on my computer (equipped with GPU Titan X)

```
import ot
import numpy as np
import time


def describeRes(r):
    print("min:{:.3E}".format(np.min(r)), "max::{:.3E}".format(np.max(r)),
          "mean::{:.3E}".format(np.mean(r)), "std::{:.3E}".format(np.std(r)))


for n in [5000, 10000, 15000, 20000, 25000, 30000]:
    print("\n", n)
    a = np.random.rand(n // 4, 100)
    b = np.random.rand(n, 100)
    time1 = time.time()
    transport = ot.da.OTDA_sinkhorn()
    transport.fit(a, b)
    G1 = transport.G
    time2 = time.time()
    transport = ot.gpu.da.OTDA_sinkhorn_GPU()
    transport.fit(a, b)
    G2 = transport.G
    time3 = time.time()
    print("Normal sinkhorn, time: {:6.2f}".format(time2 - time1), "sec")
    describeRes(G1)
    print("   GPU sinkhorn, time: {:6.2f}".format(time3 - time2), "sec")
    describeRes(G2)
```
and I obtain these results:

```
 5000
Normal sinkhorn, time:   1.21 sec
min:5.251E-12 max::8.839E-05 mean::1.600E-07 std::5.317E-07
   GPU sinkhorn, time:   0.09 sec
min:5.251E-12 max::8.839E-05 mean::1.600E-07 std::5.317E-07

 10000
Normal sinkhorn, time:   4.37 sec
min:4.508E-13 max::4.601E-05 mean::4.000E-08 std::1.366E-07
   GPU sinkhorn, time:   0.25 sec
min:4.508E-13 max::4.601E-05 mean::4.000E-08 std::1.366E-07

 15000
Normal sinkhorn, time:  10.68 sec
min:1.696E-13 max::2.031E-05 mean::1.778E-08 std::6.191E-08
   GPU sinkhorn, time:   0.49 sec
min:1.696E-13 max::2.031E-05 mean::1.778E-08 std::6.191E-08

 20000
Normal sinkhorn, time:  22.55 sec
min:1.144E-13 max::1.383E-05 mean::1.000E-08 std::3.506E-08
   GPU sinkhorn, time:   0.89 sec
min:1.144E-13 max::1.383E-05 mean::1.000E-08 std::3.506E-08

 25000
Normal sinkhorn, time:  32.90 sec
min:8.452E-14 max::8.882E-06 mean::6.400E-09 std::2.248E-08
   GPU sinkhorn, time:   1.39 sec
min:8.452E-14 max::8.882E-06 mean::6.400E-09 std::2.248E-08

 30000
Normal sinkhorn, time:  47.70 sec
min:6.306E-14 max::9.280E-06 mean::4.444E-09 std::1.572E-08
   GPU sinkhorn, time:   1.93 sec
min:6.306E-14 max::9.280E-06 mean::4.444E-09 std::1.572E-08
```

### CODE REVIEW

**Comment by AjayTalati** [comment]
Awesome :+1:

**Comment by rflamary** [comment]
Thank you Leo, I agree with Ajay that this is awesome especially the computational gain!

Nevertheless I think a few changes are necessary before merge.
+ remove the gpu submodule from ot.__init__.py since it forces the user to intall cudamat by default when doing import ot. It can still be used by doing import ot.gpu explicitely but cudamat is an optionnal dependency (same as autograd is an optional dependency of ot.dr).
+ remove the cudamat module from gpu, it should be installed independently by the user (we can easily add an explanation and a link to the github repo in the readme). This will also remove the need to update this specific module along with the devellopment and bug correction.
+ use the same function names: we can discuss this point but since the aim is to have a gpu function that can replace the numpy one with similar parameters they should have the same same (think numpy.fft.fft and scipty.fftpack.fft ) . Let python awesome namespace handle the rest.

Again this is awesome works and those changes are only small stuff. Thank you for all your work.

Rémi

**Comment by rflamary** [comment]
Hello Leo and thank you for the quick response, 

I promise these are my last comments :

+ you can keep "import cudamat" in ot.gpu.bregman and ot.gpu.da, no need for a parameter that make everything less easy to use. This will raise an ImportError uf cudadamt in not installed and it is a standard way to handle optional dependecies.

+ maybe add the sinkhorn and OTDA clas to the gpu/__init__.py file so that they can be accessed with ot.gpu.sinkhorn...

+ same with the class  OTDA_sinkhorn_GPU that should have the same name as the numpy domain adaptation class. Could you add the noem parameter to the numpy OTDA_sinkhorn implementation so that they have feature parity?

This will be  a very nice merge 

Rémi

**Comment by rflamary** [comment]
This is perfect,

I wall add a test script (your comparison ) and discuss the dependency installation in the readme.

Rémi

**Pull request merged**
