### PR TITLE
first attempt to support sphinx-gallery

### PR DESCRIPTION
**Pull request by agramfort**
@rflamary is a quick hack to make it work

I did not remove all the notebooks but it should be removed

### CODE REVIEW

**Comment by agramfort** [comment]
that was fast :)

you'll certainly have to polish

**Comment by rflamary** [comment]
Hello Alexandre,

Here is to polishing:

- I can run most of the html build (had to add a few RST title in the plot*.py files)
- I had a bug with encoding. Something about ascii decode from the accent in Peyré, I removed the accent temporarily but it would be nice to choose encoding for sphinx-gallery maybe it's in the doc but since I have an expert here...
- I have the following error that I don't understand in the current version. the error message is given below.
- The doc does not compile anymore on readthedocs do you have pointers since i cannot execute the scripts there. probably y should compile locally and add the rst files?

PS : note that it's the last time that I try a quick merge before the week end ;)

`[:~/PYTHON … /docs] master* 2 ± make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.3.6
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/objects.inv...
Executing file ../../examples/demo_OT_1D_test.py
../../examples/demo_OT_1D_test.py ran in : 0 seconds

Executing file ../../examples/demo_OT_2D_sampleslarge.py
../../examples/demo_OT_2D_sampleslarge.py ran in : 0 seconds

Executing file ../../examples/plot_OTDA_classes.py
/home/rflamary/.local/lib/python2.7/site-packages/sphinx_gallery/gen_rst.py:538: UserWarning: ________________________________________________________________________________
../../examples/plot_OTDA_classes.py failed to execute correctly:Traceback (most recent call last):
  File "/home/rflamary/.local/lib/python2.7/site-packages/sphinx_gallery/gen_rst.py", line 518, in execute_code_block
    exec(code_block, example_globals)
  File "<string>", line 50, in <module>
  File "build/bdist.linux-x86_64/egg/ot/da.py", line 728, in fit
    self.G=sinkhorn_lpl1_mm(ws,ys,wt,self.M,reg,eta,**kwargs)
  File "build/bdist.linux-x86_64/egg/ot/da.py", line 98, in sinkhorn_lpl1_mm
    for c in range(idx_begin,np.max(labels_a)+1):
TypeError: range() integer end argument expected, got numpy.float64.
________________________________________________________________________________

  warnings.warn(fail_example_warning)
../../examples/plot_OTDA_classes.py ran in : 0 seconds

Computation time summary:
	- plot_optim_OTreg.py : 0 sec
	- plot_barycenter_1D.py : 0 sec
	- plot_OT_2D_samples.py : 0 sec
	- plot_OT_1D.py : 0 sec
	- plot_OTDA_mapping_color_images.py : 0 sec
	- plot_OTDA_mapping.py : 0 sec
	- plot_OTDA_color_images.py : 0 sec
	- plot_OTDA_classes.py : 0 sec
	- plot_OTDA_2D.py : 0 sec
	- demo_OT_2D_sampleslarge.py : 0 sec
	- demo_OT_1D_test.py : 0 sec
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 16 source files that are out of date
updating environment: 16 added, 0 changed, 0 removed
reading sources... [  6%] all                                                   
Exception occurred:
  File "/home/rflamary/.local/lib/python2.7/site-packages/sphinx_gallery/gen_gallery.py", line 165, in touch_empty_backreferences
    open(examples_path, 'w').close()
IOError: [Errno 2] No such file or directory: u'/home/rflamary/PYTHON/POT/docs/source/modules/generated/ot.examples'
The full traceback has been saved in /tmp/sphinx-err-CdwtjY.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:56 : la recette pour la cible « html » a échouée
make: *** [html] Erreur 1
`

**Comment by rflamary** [comment]
Hello Alexandre,

I managed to compile the documentation locally and to use sphinx-gallery as you proposed. The current commit https://github.com/rflamary/POT/commit/17315cb08ebf777626dc9aec4bf140cfb5c42503 does not compile locally but on readthedoc [see here](http://pot.readthedocs.io/en/latest/auto_examples/index.html) If you want the documentation you need (again) to comment the mock() area in the conf.py

Thank you very much for your contribution that helped getting a better documentation for our toolbox.

**Comment by agramfort** [comment]
I'll come to your poster next week to say hi ! :)

**Pull request merged**
